// Re-export shared library components
export {
  Icon,
  type IconName,
  type IconProps,
  iconNames,
  MetallicText,
  type MetallicTextProps,
  MetallicButton,
  type MetallicButtonProps,
  MetallicCard,
  type MetallicCardProps,
  Price,
  type PriceProps,
  ProductTile,
  type ProductTileProps,
  FloatingContactButton,
  type FloatingContactButtonProps,
  CookieBanner,
  type CookieBannerProps,
} from '@scootify/shared/components';
